from enum import StrEnum


class UserLoginRejectionReason(StrEnum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    INVALID_PASSWORD_HASH = "INVALID_PASSWORD_HASH"
    INVALID_RUNTIME_USER = "INVALID_RUNTIME_USER"
