-- ============================================================
-- FleetFlow PostgreSQL schema
-- ============================================================


-- ============================================================
-- Enums
-- ============================================================

DO $$
BEGIN
    CREATE TYPE location_code AS ENUM ('SYD', 'MEL', 'ADL', 'ASP', 'BRI', 'DAR', 'PER');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE truck_model AS ENUM ('Scania', 'Man', 'Actros');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE truck_status AS ENUM ('Free', 'On the way');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE route_status AS ENUM ('PLANNED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE package_status AS ENUM ('To Do', 'In Progress', 'Done');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE user_role AS ENUM ('EMPLOYEE', 'MANAGER');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- Customers
-- ============================================================

CREATE TABLE IF NOT EXISTS public.customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    email       VARCHAR(255) NOT NULL DEFAULT '',
    phone       VARCHAR(50)  NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_email_non_empty
    ON public.customers (email)
    WHERE email <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_phone_non_empty
    ON public.customers (phone)
    WHERE phone <> '';


-- ============================================================
-- Trucks
-- vehicle_id is the domain identity, e.g. 1001, 1002, ...
-- ============================================================

CREATE TABLE IF NOT EXISTS public.trucks (
    vehicle_id       INT PRIMARY KEY,
    name             truck_model   NOT NULL,
    capacity         INT           NOT NULL CHECK (capacity > 0),
    max_range        INT           NOT NULL CHECK (max_range > 0),
    status           truck_status  NOT NULL DEFAULT 'Free',
    current_location location_code,
    busy_from        TIMESTAMP,
    busy_until       TIMESTAMP,
    in_transit_to    location_code
);

CREATE INDEX IF NOT EXISTS idx_trucks_status
    ON public.trucks(status);


-- ============================================================
-- Routes
-- Truck assignment is stored once here.
-- Repository/mapper rebuilds route.truck and truck.route in memory.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.routes (
    route_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_time   TIMESTAMP,
    status           route_status NOT NULL DEFAULT 'PLANNED',
    truck_vehicle_id INT UNIQUE REFERENCES public.trucks(vehicle_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_routes_status
    ON public.routes(status);

CREATE INDEX IF NOT EXISTS idx_routes_departure
    ON public.routes(departure_time)
    WHERE departure_time IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_routes_active
    ON public.routes(status)
    WHERE status IN ('SCHEDULED', 'IN_PROGRESS');

CREATE INDEX IF NOT EXISTS idx_routes_truck_vehicle_id
    ON public.routes(truck_vehicle_id)
    WHERE truck_vehicle_id IS NOT NULL;


-- ============================================================
-- Ordered route stops
-- A route must have at least two stops.
-- The trigger below enforces this at transaction commit.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.route_stops (
    route_id      INT NOT NULL REFERENCES public.routes(route_id) ON DELETE CASCADE,
    stop_order    INT NOT NULL CHECK (stop_order >= 0),
    location_code location_code NOT NULL,

    PRIMARY KEY (route_id, stop_order),
    UNIQUE (route_id, location_code)
);


-- ============================================================
-- Route stop count constraint trigger
--
-- Because route_stops are inserted after the route row, this check
-- must be DEFERRABLE. Repository code must insert the route and its
-- stops in the same transaction.
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_route_stop_count()
RETURNS TRIGGER AS $$
DECLARE
    route_ids_to_check INT[];
    checked_route_id   INT;
BEGIN
    IF TG_TABLE_NAME NOT IN ('routes', 'route_stops') THEN
        RAISE EXCEPTION 'check_route_stop_count cannot be used on table %.', TG_TABLE_NAME;
    END IF;

    IF TG_OP = 'DELETE' THEN
        route_ids_to_check := ARRAY[OLD.route_id];

    ELSIF TG_OP = 'UPDATE' THEN
        route_ids_to_check := ARRAY(
            SELECT DISTINCT route_id
            FROM unnest(ARRAY[OLD.route_id, NEW.route_id]) AS route_id
        );

    ELSE
        -- INSERT on routes: NEW.route_id is the route primary key.
        -- INSERT on route_stops: NEW.route_id is the route foreign key.
        route_ids_to_check := ARRAY[NEW.route_id];
    END IF;

    FOREACH checked_route_id IN ARRAY route_ids_to_check LOOP
        -- Skip checks for routes that no longer exist, e.g. route delete cascaded stops.
        IF EXISTS (
            SELECT 1
            FROM public.routes
            WHERE route_id = checked_route_id
        ) THEN
            IF (
                SELECT COUNT(*)
                FROM public.route_stops
                WHERE route_id = checked_route_id
            ) < 2 THEN
                RAISE EXCEPTION 'Route % must have at least two stops.', checked_route_id
                    USING ERRCODE = '23514';
            END IF;
        END IF;
    END LOOP;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


DROP TRIGGER IF EXISTS trg_check_route_stop_count_on_routes ON public.routes;

CREATE CONSTRAINT TRIGGER trg_check_route_stop_count_on_routes
AFTER INSERT OR UPDATE ON public.routes
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.check_route_stop_count();


DROP TRIGGER IF EXISTS trg_check_route_stop_count_on_route_stops ON public.route_stops;

CREATE CONSTRAINT TRIGGER trg_check_route_stop_count_on_route_stops
AFTER INSERT OR UPDATE OR DELETE ON public.route_stops
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION public.check_route_stop_count();


-- ============================================================
-- Packages
-- ============================================================

CREATE TABLE IF NOT EXISTS public.packages (
    package_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_location   location_code   NOT NULL,
    end_location     location_code   NOT NULL,
    weight           DECIMAL(8, 2)   NOT NULL CHECK (weight > 0),
    status           package_status  NOT NULL DEFAULT 'To Do',
    current_location location_code,
    expected_arrival TIMESTAMP,
    customer_id      INT NOT NULL REFERENCES public.customers(customer_id),
    route_id         INT REFERENCES public.routes(route_id) ON DELETE SET NULL,

    CONSTRAINT chk_package_locations CHECK (start_location <> end_location)
);

CREATE INDEX IF NOT EXISTS idx_packages_route_id
    ON public.packages(route_id);

CREATE INDEX IF NOT EXISTS idx_packages_customer_id
    ON public.packages(customer_id);

CREATE INDEX IF NOT EXISTS idx_packages_status
    ON public.packages(status);

CREATE INDEX IF NOT EXISTS idx_packages_in_transit
    ON public.packages(status, route_id)
    WHERE status = 'In Progress';


-- ============================================================
-- Users
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
    user_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    role          user_role    NOT NULL DEFAULT 'EMPLOYEE',
    name          VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL DEFAULT '',
    phone         VARCHAR(50)  NOT NULL DEFAULT '',
    password_hash TEXT         NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_non_empty
    ON public.users(email)
    WHERE email <> '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone_non_empty
    ON public.users(phone)
    WHERE phone <> '';
